import { prisma } from '../src/utils/prisma.js';
import { computeWorkOrderCosts, roundMoney } from '../src/utils/costRules.js';
import { generatePmWorkOrder } from '../src/services/pmGeneration.js';

let failures = 0;

function check(name: string, ok: boolean, detail = ''): void {
  if (!ok) failures += 1;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${detail ? `  [${detail}]` : ''}`);
}

/** What the base relations say a work order is worth, computed independently of
 *  the cache and of the code path under test. */
async function derive(workOrderId: string): Promise<number> {
  const [operations, woMaterials, externalServices, laborEntries] = await Promise.all([
    prisma.workOrderOperation.findMany({ where: { workOrderId, isDeleted: false }, include: { craft: true } }),
    prisma.workOrderMaterial.findMany({ where: { workOrderId, isDeleted: false } }),
    prisma.externalServiceCost.findMany({ where: { workOrderId, isDeleted: false } }),
    prisma.laborEntry.findMany({ where: { isDeleted: false, operation: { workOrderId, isDeleted: false } }, include: { operation: { include: { craft: true } } } }),
  ]);
  return roundMoney(computeWorkOrderCosts({ operations, woMaterials, externalServices, laborEntries } as never).plannedCost);
}

/**
 * Removes every row this script created, whether or not the checks passed.
 *
 * This exists because a probe that only cleans up on the happy path is a probe
 * that eventually leaks into the live database, and a leaked plan is worse than
 * a leaked work order: every later scheduler run evaluates it and mints another
 * work order that no test owns. That is not hypothetical - an early run of this
 * script failed on a foreign-key error after creating its plan, left plan
 * R9A-1790782065395 behind, and a later gate run generated WO-000774 and
 * WO-000775 from it.
 *
 * Rows are found from the fixture ids rather than from return values, so a
 * throw between the create and the read cannot strand a work order whose id
 * never made it back. Each delete is attempted independently: one unexpected
 * row type must not leave the other twenty tables untouched, which is exactly
 * how the original leak stayed invisible.
 */
async function removeFixtures(ids: { taskListId?: string; planId?: string }): Promise<void> {
  const planIds = ids.planId ? [ids.planId] : [];
  const taskListIds = ids.taskListId ? [ids.taskListId] : [];
  if (planIds.length === 0 && taskListIds.length === 0) return;

  // Anything raised from these plans, including a work order generated by a
  // concurrent scheduler run rather than by this script.
  const woIds = (
    await prisma.workOrder.findMany({ where: { sourcePlanId: { in: planIds } }, select: { workOrderId: true } })
  ).map((w) => w.workOrderId);
  const opIds = (
    await prisma.workOrderOperation.findMany({ where: { workOrderId: { in: woIds } }, select: { operationId: true } })
  ).map((o) => o.operationId);

  const steps: [string, () => Promise<unknown>][] = [
    // Children of the work order first: operations and snapshots restrict it.
    ['workOrderSnapshot', () => prisma.workOrderSnapshot.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['costSplit', () => prisma.costSplit.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['workOrderChecklist', () => prisma.workOrderChecklist.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['workOrderNotifLink', () => prisma.workOrderNotifLink.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['externalServiceCost', () => prisma.externalServiceCost.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['workOrderMaterial', () => prisma.workOrderMaterial.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['laborEntry', () => prisma.laborEntry.deleteMany({ where: { operationId: { in: opIds } } })],
    ['workOrderOperation', () => prisma.workOrderOperation.deleteMany({ where: { workOrderId: { in: woIds } } })],
    ['workOrder', () => prisma.workOrder.deleteMany({ where: { workOrderId: { in: woIds } } })],
    // Children of the plan: targets cascade, but deleting them explicitly keeps
    // the order obvious and survives someone changing that cascade later.
    ['maintenancePlanTarget', () => prisma.maintenancePlanTarget.deleteMany({ where: { planId: { in: planIds } } })],
    ['maintenancePlanMeter', () => prisma.maintenancePlanMeter.deleteMany({ where: { planId: { in: planIds } } })],
    ['maintenancePlan', () => prisma.maintenancePlan.deleteMany({ where: { planId: { in: planIds } } })],
    ['taskListOperation', () => prisma.taskListOperation.deleteMany({ where: { taskListId: { in: taskListIds } } })],
    ['taskList', () => prisma.taskList.deleteMany({ where: { taskListId: { in: taskListIds } } })],
    // Audit rows hold no foreign key, so nothing else removes them. A row
    // describing a plan that no longer exists is a row that lies.
    ['auditLogEntry', () => prisma.auditLogEntry.deleteMany({ where: { recordId: { in: [...woIds, ...planIds, ...taskListIds] } } })],
  ];

  const stranded: string[] = [];
  for (const [label, run] of steps) {
    try {
      await run();
    } catch (error) {
      stranded.push(`${label}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }

  if (stranded.length > 0) {
    console.error(`\nFAIL  ${stranded.length} cleanup step(s) could not run - probe rows may remain:`);
    for (const s of stranded) console.error(`      ${s}`);
    process.exitCode = 1;
    return;
  }

  console.log(`\nprobe rows removed (${woIds.length} work order(s), plan ${planIds.join(',') || 'none'}, task list ${taskListIds.join(',') || 'none'})`);
}

async function main(): Promise<void> {
  // The live database may or may not hold maintenance plans; a previous test
  // run can leave one behind, and this script must not depend on that either
  // way. It builds the plan it needs and removes it in a finally, so the check
  // does not depend on leftover state. What it proves is the part that only a
  // real transaction can prove - that the recompute sees the operations the
  // same transaction created, and that its audit row satisfies a real foreign
  // key.
  const [supervisor, location, equipment, workCenter, craft] = await Promise.all([
    prisma.user.findFirst({ where: { isDeleted: false }, select: { userId: true } }),
    prisma.functionalLocation.findFirst({ where: { isDeleted: false }, select: { functionalLocationId: true } }),
    prisma.equipment.findFirst({ where: { isDeleted: false }, select: { equipmentId: true } }),
    prisma.workCenter.findFirst({ where: { isDeleted: false }, select: { workCenterId: true } }),
    prisma.craft.findFirst({ where: { isDeleted: false }, select: { craftId: true, hourlyRate: true }, orderBy: { hourlyRate: 'desc' } }),
  ]);

  if (!supervisor || !location || !equipment || !workCenter || !craft) {
    check('master data available (user, location, equipment, work centre, craft)', false, 'seed data missing');
    process.exitCode = 1;
    return;
  }

  // One stamp for both rows: a leaked fixture should be identifiable as a pair.
  const stamp = Date.now();
  const fixtures: { taskListId?: string; planId?: string } = {};

  try {
    const rate = Number(craft.hourlyRate);
    const taskList = await prisma.taskList.create({
      data: {
        code: `R9A-${stamp}`,
        description: 'R.9 A probe',
        workCenterId: workCenter.workCenterId,
        operations: {
          create: [
            { sequenceNumber: 10, description: 'probe a', craftId: craft.craftId, plannedHours: 1.5, numberOfTechnicians: 1, createdBy: supervisor.userId, modifiedBy: supervisor.userId },
            { sequenceNumber: 20, description: 'probe b', craftId: craft.craftId, plannedHours: 0.5, numberOfTechnicians: 1, createdBy: supervisor.userId, modifiedBy: supervisor.userId },
          ],
        },
      },
    });
    fixtures.taskListId = taskList.taskListId;

    const plan = await prisma.maintenancePlan.create({
      data: {
        planCode: `R9A-${stamp}`,
        description: 'R.9 A probe plan',
        workCenterId: workCenter.workCenterId,
        equipmentId: equipment.equipmentId,
        functionalLocationId: location.functionalLocationId,
        taskListId: taskList.taskListId,
        strategyType: 'Time',
        intervalValue: 30,
        intervalUnit: 'Days',
        startDate: new Date('2026-09-01T00:00:00.000Z'),
        priority: 'Medium',
        generatedWorkOrderStatus: 'Draft',
        createdBy: supervisor.userId,
        modifiedBy: supervisor.userId,
        targets: {
          create: [{ equipmentId: equipment.equipmentId, createdBy: supervisor.userId, modifiedBy: supervisor.userId }],
        },
      },
    });
    fixtures.planId = plan.planId;

    const expected = roundMoney(2 * rate);
    console.log(`plan ${plan.planCode}: 2 operations at ${rate}/h -> expected planned ${expected}`);

    const result = await generatePmWorkOrder(prisma, {
      planId: plan.planId,
      cycleKey: '2026-09-30#R9A',
      basis: 'Time',
      actorUserId: 'scheduler',
    });

    check('a work order was generated, not skipped', result.created === true, result.skipReason ?? '');


    const generated = await prisma.workOrder.findUnique({ where: { workOrderId: result.workOrderId } });
    if (!generated) {
      // Not an early return: the finally below still has to run, and the
      // summary at the end still has to print.
      check('the generated work order exists', false);
    } else {
      const stored = roundMoney(Number(generated.plannedCost));
      const derived = await derive(result.workOrderId);

      check('stored plannedCost equals the figure derived from its own operations', stored === derived, `stored=${stored} derived=${derived}`);
      check('stored plannedCost equals the hand-computed 2 x rate', stored === expected, `stored=${stored} expected=${expected}`);
      check('the stored figure is not the default zero', stored > 0, `stored=${stored}`);
      check('createdBy keeps the scheduler label', generated.createdBy === 'scheduler', generated.createdBy);
      check('the supervisor is what the foreign keys carry', generated.supervisorUserId === supervisor.userId, generated.supervisorUserId ?? 'null');

      const audit = await prisma.auditLogEntry.findMany({
        where: { recordId: result.workOrderId, fieldName: 'plannedCost' },
      });
      check('the cost change wrote an audit row naming the field', audit.length === 1, `${audit.length} row(s)`);
      check('the audit row names a real user, not the scheduler label', audit[0]?.userId === supervisor.userId, audit[0]?.userId ?? 'none');
      check('the audit row records the move from zero', audit[0]?.oldValue === '0' && audit[0]?.newValue === String(stored), `${audit[0]?.oldValue} -> ${audit[0]?.newValue}`);

      // A second generation for the same cycle is a skip, and must not write a
      // cost or an audit row: the idempotency guard has to come first.
      const again = await generatePmWorkOrder(prisma, { planId: plan.planId, cycleKey: '2026-09-30#R9A', basis: 'Time', actorUserId: 'scheduler' });
      check('the same cycle is skipped, not regenerated', again.created === false, again.skipReason ?? '');
      const auditAfter = await prisma.auditLogEntry.count({ where: { recordId: result.workOrderId, fieldName: 'plannedCost' } });
      check('a skipped generation writes no second audit row', auditAfter === 1, `${auditAfter} row(s)`);

      console.log(`\ngenerated ${generated.woNumber}: stored planned=${stored} derived=${derived}`);
    }
  } finally {
    await removeFixtures(fixtures);
  }

  console.log(`\n${failures === 0 ? 'all checks passed' : `${failures} check(s) failed`}`);
  if (failures > 0) process.exitCode = 1;
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
