/** Database plumbing for the trial run: an opt-in, throwaway schema on the
 * configured PostgreSQL server, migrated and dropped by this run. Never prints a
 * connection string or any credential. */
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { PrismaClient } from '@prisma/client';
import { backendDir } from './env.js';

const bin = (name: string): string =>
  path.join(backendDir, 'node_modules', '.bin', name + (process.platform === 'win32' ? '.cmd' : ''));

export function makeClient(url: string): PrismaClient {
  return new PrismaClient({ datasources: { db: { url } } });
}

/** The trial runs in a dedicated schema on the same server, so nothing shared
 * with the app's `public` schema is touched. */
export function trialUrl(baseUrl: string, schema: string): string {
  const url = new URL(baseUrl);
  url.searchParams.set('schema', schema);
  return url.toString();
}

export async function createTrialSchema(client: PrismaClient, schema: string): Promise<void> {
  // Schema names are generated by the harness (cmms_trial_<pid>_<ms>) and can
  // only contain word characters; quoting keeps the statement honest anyway.
  await client.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`);
}

export async function dropTrialSchema(client: PrismaClient, schema: string): Promise<void> {
  await client.$executeRawUnsafe(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
}

export function migrateTrial(trialUrlValue: string): { ok: boolean; detail: string } {
  const commandLine =
    process.platform === 'win32'
      ? `"${bin('prisma')}" migrate deploy`
      : `${bin('prisma')} migrate deploy`;
  const r = spawnSync(commandLine, {
    cwd: backendDir,
    shell: process.platform === 'win32',
    env: { ...process.env, DATABASE_URL: trialUrlValue },
    encoding: 'utf8',
  });
  if (r.status !== 0) {
    return { ok: false, detail: `prisma migrate deploy exited ${r.status}` };
  }
  return { ok: true, detail: 'ok' };
}